name: Cypress Tests for ServeRest
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress tests
        run: npm run test
      - name: Generate single file Allure Report
        if: ${{ !cancelled() }}
        run: npm run report:export
      - name: Upload Allure Report
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: Allure Report
          path: artifacts/reports/allure/allure-report-single
          retention-days: 30
          overwrite: true
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Upload logs
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: Automation Logs
          path: artifacts/logs/
          retention-days: 30
          overwrite: true
      - name: Upload screenshots
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: Automation Screenshots
          path: artifacts/screenshots/
          retention-days: 30
          overwrite: true
          if-no-files-found: ignore
      - name: Upload videos
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: Automation Screenshots
          path: artifacts/screenshots/
          retention-days: 30
          overwrite: true
          if-no-files-found: ignore
